#!/usr/bin/env python3
"""
capture.py - fetch every 'file' source, validate it, hash it, and (re)generate the
manifest, provenance, and chain of custody.

Needs network. A reader never has to run this; they run verify.py and build.py, which need
nothing but the repo. This is the reporter's tool for building the archive in the first place.

    python 03-harness/capture.py            # fetch missing sources, hash, regenerate manifests
    python 03-harness/capture.py --force    # re-fetch everything

Validation, not just transport: a 200 is not proof of the right document. A '.pdf' must begin
with %PDF-; anything that fails is quarantined (.rejected) and recorded, never hashed as if it
were a source. Wayback URLs are pulled from the availability API, with a best-effort save for
sources that have no snapshot yet.
"""
import argparse, datetime, hashlib, json, pathlib, sys, time

try:
    import requests
except ImportError:
    print("capture.py needs `requests` (pip install requests). verify.py and build.py do not.")
    sys.exit(2)

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

ap = argparse.ArgumentParser()
ap.add_argument("--force", action="store_true", help="re-fetch even sources already captured")
ARGS = ap.parse_args()

ROOT = pathlib.Path(__file__).resolve().parent.parent
ARCH = ROOT / "01-sources-archive"
RAW = ARCH / "raw"
RAW.mkdir(parents=True, exist_ok=True)
CFG = json.loads((ARCH / "sources.json").read_text(encoding="utf-8"))
UA = {"User-Agent": "Mozilla/5.0 (trustless-archive capture.py; Pittsburgh Water Deliberation Record)"}

MAGIC = {"pdf": b"%PDF-"}


def sha256(b):
    return hashlib.sha256(b).hexdigest()


def now():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def custody(line):
    with open(ARCH / "CHAIN-OF-CUSTODY.md", "a", encoding="utf-8") as f:
        f.write(f"- {now()}  {line}\n")


def wayback(url):
    """An existing snapshot if one exists, else a best-effort save, else None."""
    try:
        r = requests.get("https://archive.org/wayback/available", params={"url": url},
                         headers=UA, timeout=20)
        snap = r.json().get("archived_snapshots", {}).get("closest", {})
        if snap.get("available") and snap.get("url"):
            return snap["url"].replace("http://", "https://")
    except Exception:
        pass
    try:
        r = requests.get("https://web.archive.org/save/" + url, headers=UA, timeout=45,
                         allow_redirects=True)
        cl = r.headers.get("Content-Location")
        if cl:
            return "https://web.archive.org" + cl
    except Exception:
        pass
    return None


def main():
    captured, rejected = [], []
    for s in CFG["sources"]:
        if s.get("mode") != "file":
            continue
        dest = ARCH / s["path"]
        if dest.exists() and not ARGS.force:
            print(f"have    {s['id']}")
            captured.append(s)
            continue
        print(f"fetch   {s['id']}  {s['url']}")
        try:
            r = requests.get(s["url"], headers=UA, timeout=60, allow_redirects=True)
            r.raise_for_status()
            body = r.content
        except Exception as e:
            print(f"  FAILED  {type(e).__name__}: {e}")
            custody(f"FETCH FAILED  {s['id']}  {type(e).__name__}")
            continue
        magic = MAGIC.get(s.get("type", ""))
        if magic and not body.startswith(magic):
            q = dest.with_suffix(dest.suffix + ".rejected")
            q.write_bytes(body)
            print(f"  REJECTED  did not start with {magic!r}; quarantined {q.name}")
            custody(f"REJECTED  {s['id']}  content did not validate as {s.get('type')}")
            rejected.append(s)
            continue
        dest.write_bytes(body)
        h = sha256(body)
        (dest.with_suffix(dest.suffix + ".sha256")).write_text(f"{h}  {dest.name}\n", encoding="utf-8")
        print(f"  ok  {len(body):,} bytes  {h[:16]}...")
        custody(f"CAPTURED  {s['id']}  {len(body)} bytes  sha256 {h}")
        captured.append(s)
        time.sleep(0.5)

    # --- Wayback pass for every source (file and citation) --------------------------
    print("\nWayback:")
    waybacks = {}
    for s in CFG["sources"]:
        wb = wayback(s["url"])
        waybacks[s["id"]] = wb
        print(f"  {'ok ' if wb else 'no '} {s['id']}")
        time.sleep(0.3)

    # --- MANIFEST.md (deterministic body: sorted, no wall clock) --------------------
    lines = ["# MANIFEST", "",
             "SHA-256 of every captured source file. Generated by capture.py; never hand-edited.",
             "Re-run `python 03-harness/verify.py` to confirm these against the files on disk.", ""]
    for s in sorted([x for x in CFG["sources"] if x.get("mode") == "file"], key=lambda x: x["id"]):
        p = ARCH / s["path"]
        side = p.with_suffix(p.suffix + ".sha256")
        h = side.read_text(encoding="utf-8").split()[0] if side.exists() else "NOT CAPTURED"
        lines.append(f"- `{s['id']}` `{s['path']}`  {h}")
    (ARCH / "MANIFEST.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # --- PROVENANCE.md (deterministic body) -----------------------------------------
    plines = ["# PROVENANCE", "",
              "Origin and Wayback citation for every source. Generated by capture.py.", ""]
    for s in CFG["sources"]:
        wb = waybacks.get(s["id"])
        plines.append(f"## `{s['id']}`")
        plines.append(f"- Title: {s['title']}")
        plines.append(f"- Origin: <{s['url']}>")
        plines.append(f"- Wayback: <{wb}>" if wb else "- Wayback: PENDING (no snapshot yet; re-run capture.py)")
        if s.get("note"):
            plines.append(f"- Note: {s['note']}")
        plines.append("")
    (ARCH / "PROVENANCE.md").write_text("\n".join(plines) + "\n", encoding="utf-8")

    print(f"\n{len(captured)} captured, {len(rejected)} rejected.")
    print("Regenerated MANIFEST.md and PROVENANCE.md. Run verify.py to confirm.")


if __name__ == "__main__":
    main()
